services:
  - type: web
    name: ibex-demo
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ibex-postgres
          property: connectionString

databases:
  - name: ibex-postgres
    databaseName: ibex
    user: ibex
    plan: free
